### PR TITLE
Update Install or Defer.sh

### PR DESCRIPTION
**Pull request by just-some-tall-bloke**
Allows connectivity check to pass on corporate networks where ping is blocked

### CODE REVIEW

**Comment by homebysix** [comment]
Thanks! Do you know whether this should work on old macOS versions as well?

And do you mind using the same OpenDNS IP address instead of google.com, for consistency?

**Comment by mpanighetti** [comment]
Looks like macOS has included netcat in the default install as of 10.13, which is our minimum OS requirement, so that should work fine as a replacement.

**Comment by just-some-tall-bloke** [comment]
Using an IP is pretty limited outside of pinging it. Perhaps a reasonable compromise would be to switch google.com for apple.com, as that's the domain we're concerned about connecting to

**Comment by mpanighetti** [comment]
Would it be possible to test directly against Apple's software update servers (by hostname or IP), rather than testing google.com/apple.com/OpenDNS to try and determine whether the Mac can check for updates? We could also just move the testing phase to the actual update check, and exit with error if that check errors out for connectivity issues.

**Comment by just-some-tall-bloke** [comment]
We can indeed. Edited the URL to point to swscan.apple.com

**Review by homebysix — APPROVED** [review]

**Pull request merged**
